# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\unhealthy\Documents\GitHub\myClientPyQt\BrowerserWidgetMainPageQt.ui'
#
# Created: Sat Mar  2 10:55:34 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 585)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 585))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("src/logo_school.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setMinimumSize(QtCore.QSize(1000, 562))
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralWidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1000, 562))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.mainPage = QtGui.QWidget()
        self.mainPage.setMinimumSize(QtCore.QSize(995, 562))
        self.mainPage.setObjectName(_fromUtf8("mainPage"))
        self.verticalLayout = QtGui.QVBoxLayout(self.mainPage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.schoolLogolabel_2 = QtGui.QLabel(self.mainPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schoolLogolabel_2.sizePolicy().hasHeightForWidth())
        self.schoolLogolabel_2.setSizePolicy(sizePolicy)
        self.schoolLogolabel_2.setMinimumSize(QtCore.QSize(801, 71))
        self.schoolLogolabel_2.setText(_fromUtf8(""))
        self.schoolLogolabel_2.setPixmap(QtGui.QPixmap(_fromUtf8("src/long_logo_school.png")))
        self.schoolLogolabel_2.setScaledContents(False)
        self.schoolLogolabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.schoolLogolabel_2.setObjectName(_fromUtf8("schoolLogolabel_2"))
        self.horizontalLayout_9.addWidget(self.schoolLogolabel_2)
        spacerItem1 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.welcomePageLabel = QtGui.QLabel(self.mainPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcomePageLabel.sizePolicy().hasHeightForWidth())
        self.welcomePageLabel.setSizePolicy(sizePolicy)
        self.welcomePageLabel.setMinimumSize(QtCore.QSize(361, 251))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.welcomePageLabel.setFont(font)
        self.welcomePageLabel.setFrameShape(QtGui.QFrame.Box)
        self.welcomePageLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.welcomePageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomePageLabel.setObjectName(_fromUtf8("welcomePageLabel"))
        self.horizontalLayout.addWidget(self.welcomePageLabel)
        spacerItem4 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.calendarWidget = QtGui.QCalendarWidget(self.mainPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMinimumSize(QtCore.QSize(361, 251))
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.horizontalLayout.addWidget(self.calendarWidget)
        spacerItem5 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem6 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.cjPushButton = QtGui.QPushButton(self.mainPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cjPushButton.sizePolicy().hasHeightForWidth())
        self.cjPushButton.setSizePolicy(sizePolicy)
        self.cjPushButton.setMinimumSize(QtCore.QSize(75, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cjPushButton.setFont(font)
        self.cjPushButton.setObjectName(_fromUtf8("cjPushButton"))
        self.horizontalLayout_4.addWidget(self.cjPushButton)
        self.kbPushButton = QtGui.QPushButton(self.mainPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kbPushButton.sizePolicy().hasHeightForWidth())
        self.kbPushButton.setSizePolicy(sizePolicy)
        self.kbPushButton.setMinimumSize(QtCore.QSize(75, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kbPushButton.setFont(font)
        self.kbPushButton.setObjectName(_fromUtf8("kbPushButton"))
        self.horizontalLayout_4.addWidget(self.kbPushButton)
        self.yxkcPushButton = QtGui.QPushButton(self.mainPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yxkcPushButton.sizePolicy().hasHeightForWidth())
        self.yxkcPushButton.setSizePolicy(sizePolicy)
        self.yxkcPushButton.setMinimumSize(QtCore.QSize(75, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yxkcPushButton.setFont(font)
        self.yxkcPushButton.setObjectName(_fromUtf8("yxkcPushButton"))
        self.horizontalLayout_4.addWidget(self.yxkcPushButton)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem9 = QtGui.QSpacerItem(20, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem9)
        self.stackedWidget.addWidget(self.mainPage)
        self.loadingPage = QtGui.QWidget()
        self.loadingPage.setMinimumSize(QtCore.QSize(995, 562))
        self.loadingPage.setObjectName(_fromUtf8("loadingPage"))
        self.gridLayout_3 = QtGui.QGridLayout(self.loadingPage)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 1, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 138, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem11, 0, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.loadingLabel = QtGui.QLabel(self.loadingPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadingLabel.sizePolicy().hasHeightForWidth())
        self.loadingLabel.setSizePolicy(sizePolicy)
        self.loadingLabel.setMinimumSize(QtCore.QSize(591, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Kristen ITC"))
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.loadingLabel.setFont(font)
        self.loadingLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.loadingLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.loadingLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.loadingLabel.setObjectName(_fromUtf8("loadingLabel"))
        self.verticalLayout_2.addWidget(self.loadingLabel)
        self.progressBar = QtGui.QProgressBar(self.loadingPage)
        self.progressBar.setMinimumSize(QtCore.QSize(521, 41))
        self.progressBar.setProperty("value", 33)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 278, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem13, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.loadingPage)
        self.cjPage = QtGui.QWidget()
        self.cjPage.setMinimumSize(QtCore.QSize(995, 562))
        self.cjPage.setObjectName(_fromUtf8("cjPage"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.cjPage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.userImformationLabel = QtGui.QLabel(self.cjPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userImformationLabel.sizePolicy().hasHeightForWidth())
        self.userImformationLabel.setSizePolicy(sizePolicy)
        self.userImformationLabel.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.userImformationLabel.setFont(font)
        self.userImformationLabel.setObjectName(_fromUtf8("userImformationLabel"))
        self.verticalLayout_3.addWidget(self.userImformationLabel)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.xnOpptionLabel = QtGui.QLabel(self.cjPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xnOpptionLabel.sizePolicy().hasHeightForWidth())
        self.xnOpptionLabel.setSizePolicy(sizePolicy)
        self.xnOpptionLabel.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(14)
        self.xnOpptionLabel.setFont(font)
        self.xnOpptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xnOpptionLabel.setObjectName(_fromUtf8("xnOpptionLabel"))
        self.horizontalLayout_17.addWidget(self.xnOpptionLabel)
        self.xnOpptionComboBox = QtGui.QComboBox(self.cjPage)
        self.xnOpptionComboBox.setMinimumSize(QtCore.QSize(131, 25))
        self.xnOpptionComboBox.setEditable(False)
        self.xnOpptionComboBox.setObjectName(_fromUtf8("xnOpptionComboBox"))
        self.xnOpptionComboBox.addItem(_fromUtf8(""))
        self.xnOpptionComboBox.addItem(_fromUtf8(""))
        self.xnOpptionComboBox.addItem(_fromUtf8(""))
        self.xnOpptionComboBox.addItem(_fromUtf8(""))
        self.xnOpptionComboBox.addItem(_fromUtf8(""))
        self.xnOpptionComboBox.addItem(_fromUtf8(""))
        self.xnOpptionComboBox.addItem(_fromUtf8(""))
        self.xnOpptionComboBox.addItem(_fromUtf8(""))
        self.xnOpptionComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.xnOpptionComboBox)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_17)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.xqOpptionLabel = QtGui.QLabel(self.cjPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xqOpptionLabel.sizePolicy().hasHeightForWidth())
        self.xqOpptionLabel.setSizePolicy(sizePolicy)
        self.xqOpptionLabel.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(14)
        self.xqOpptionLabel.setFont(font)
        self.xqOpptionLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.xqOpptionLabel.setScaledContents(False)
        self.xqOpptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xqOpptionLabel.setObjectName(_fromUtf8("xqOpptionLabel"))
        self.horizontalLayout_18.addWidget(self.xqOpptionLabel)
        self.xqOpptionComboBox = QtGui.QComboBox(self.cjPage)
        self.xqOpptionComboBox.setMinimumSize(QtCore.QSize(131, 25))
        self.xqOpptionComboBox.setObjectName(_fromUtf8("xqOpptionComboBox"))
        self.xqOpptionComboBox.addItem(_fromUtf8(""))
        self.xqOpptionComboBox.addItem(_fromUtf8(""))
        self.xqOpptionComboBox.addItem(_fromUtf8(""))
        self.xqOpptionComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_18.addWidget(self.xqOpptionComboBox)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_18)
        spacerItem15 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.lnCjPushButton = QtGui.QPushButton(self.cjPage)
        self.lnCjPushButton.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        self.lnCjPushButton.setFont(font)
        self.lnCjPushButton.setObjectName(_fromUtf8("lnCjPushButton"))
        self.horizontalLayout_5.addWidget(self.lnCjPushButton)
        self.cjBackPushButton = QtGui.QPushButton(self.cjPage)
        self.cjBackPushButton.setObjectName(_fromUtf8("cjBackPushButton"))
        self.horizontalLayout_5.addWidget(self.cjBackPushButton)
        spacerItem16 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.cjGroupBox_2 = QtGui.QGroupBox(self.cjPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cjGroupBox_2.sizePolicy().hasHeightForWidth())
        self.cjGroupBox_2.setSizePolicy(sizePolicy)
        self.cjGroupBox_2.setMinimumSize(QtCore.QSize(980, 360))
        self.cjGroupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.cjGroupBox_2.setFont(font)
        self.cjGroupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cjGroupBox_2.setObjectName(_fromUtf8("cjGroupBox_2"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.cjGroupBox_2)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.cjTabelView = QtGui.QTableView(self.cjGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cjTabelView.sizePolicy().hasHeightForWidth())
        self.cjTabelView.setSizePolicy(sizePolicy)
        self.cjTabelView.setMinimumSize(QtCore.QSize(960, 331))
        self.cjTabelView.setFrameShadow(QtGui.QFrame.Sunken)
        self.cjTabelView.setAutoScroll(True)
        self.cjTabelView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.cjTabelView.setProperty("showDropIndicator", True)
        self.cjTabelView.setAlternatingRowColors(False)
        self.cjTabelView.setShowGrid(True)
        self.cjTabelView.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.cjTabelView.setSortingEnabled(False)
        self.cjTabelView.setWordWrap(True)
        self.cjTabelView.setCornerButtonEnabled(True)
        self.cjTabelView.setObjectName(_fromUtf8("cjTabelView"))
        self.verticalLayout_17.addWidget(self.cjTabelView)
        self.verticalLayout_3.addWidget(self.cjGroupBox_2)
        self.userGPALabel = QtGui.QLabel(self.cjPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userGPALabel.sizePolicy().hasHeightForWidth())
        self.userGPALabel.setSizePolicy(sizePolicy)
        self.userGPALabel.setMinimumSize(QtCore.QSize(980, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(14)
        font.setItalic(False)
        self.userGPALabel.setFont(font)
        self.userGPALabel.setObjectName(_fromUtf8("userGPALabel"))
        self.verticalLayout_3.addWidget(self.userGPALabel)
        self.stackedWidget.addWidget(self.cjPage)
        self.kbPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kbPage.sizePolicy().hasHeightForWidth())
        self.kbPage.setSizePolicy(sizePolicy)
        self.kbPage.setMinimumSize(QtCore.QSize(995, 562))
        self.kbPage.setObjectName(_fromUtf8("kbPage"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.kbPage)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.kbImformationLabel = QtGui.QLabel(self.kbPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kbImformationLabel.sizePolicy().hasHeightForWidth())
        self.kbImformationLabel.setSizePolicy(sizePolicy)
        self.kbImformationLabel.setMinimumSize(QtCore.QSize(281, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        self.kbImformationLabel.setFont(font)
        self.kbImformationLabel.setObjectName(_fromUtf8("kbImformationLabel"))
        self.horizontalLayout_7.addWidget(self.kbImformationLabel)
        self.kbBackPushButton = QtGui.QPushButton(self.kbPage)
        self.kbBackPushButton.setObjectName(_fromUtf8("kbBackPushButton"))
        self.horizontalLayout_7.addWidget(self.kbBackPushButton)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.tabWidget = QtGui.QTabWidget(self.kbPage)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.kbTableView = QtGui.QTableView(self.tab)
        self.kbTableView.setMinimumSize(QtCore.QSize(975, 480))
        self.kbTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.kbTableView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.kbTableView.setObjectName(_fromUtf8("kbTableView"))
        self.verticalLayout_8.addWidget(self.kbTableView)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.sjkTableView = QtGui.QTableView(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sjkTableView.sizePolicy().hasHeightForWidth())
        self.sjkTableView.setSizePolicy(sizePolicy)
        self.sjkTableView.setObjectName(_fromUtf8("sjkTableView"))
        self.verticalLayout_9.addWidget(self.sjkTableView)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem19)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_3.sizePolicy().hasHeightForWidth())
        self.tab_3.setSizePolicy(sizePolicy)
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.sxkTableView = QtGui.QTableView(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sxkTableView.sizePolicy().hasHeightForWidth())
        self.sxkTableView.setSizePolicy(sizePolicy)
        self.sxkTableView.setObjectName(_fromUtf8("sxkTableView"))
        self.verticalLayout_10.addWidget(self.sxkTableView)
        spacerItem20 = QtGui.QSpacerItem(20, 248, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem20)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_4.sizePolicy().hasHeightForWidth())
        self.tab_4.setSizePolicy(sizePolicy)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.wapTableView = QtGui.QTableView(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wapTableView.sizePolicy().hasHeightForWidth())
        self.wapTableView.setSizePolicy(sizePolicy)
        self.wapTableView.setObjectName(_fromUtf8("wapTableView"))
        self.verticalLayout_11.addWidget(self.wapTableView)
        spacerItem21 = QtGui.QSpacerItem(20, 248, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem21)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.kbPage)
        self.yxkcPage = QtGui.QWidget()
        self.yxkcPage.setMinimumSize(QtCore.QSize(995, 562))
        self.yxkcPage.setObjectName(_fromUtf8("yxkcPage"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.yxkcPage)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem22)
        self.label = QtGui.QLabel(self.yxkcPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(760, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.yxkcBackPushButton = QtGui.QPushButton(self.yxkcPage)
        self.yxkcBackPushButton.setObjectName(_fromUtf8("yxkcBackPushButton"))
        self.horizontalLayout_3.addWidget(self.yxkcBackPushButton)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem23)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.yxkcGroupBox = QtGui.QGroupBox(self.yxkcPage)
        self.yxkcGroupBox.setObjectName(_fromUtf8("yxkcGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.yxkcGroupBox)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.yxkcTableView = QtGui.QTableView(self.yxkcGroupBox)
        self.yxkcTableView.setMinimumSize(QtCore.QSize(960, 430))
        self.yxkcTableView.setObjectName(_fromUtf8("yxkcTableView"))
        self.gridLayout.addWidget(self.yxkcTableView, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.yxkcGroupBox)
        self.stackedWidget.addWidget(self.yxkcPage)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.cjAction = QtGui.QAction(MainWindow)
        self.cjAction.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.cjAction.setObjectName(_fromUtf8("cjAction"))
        self.kbAction = QtGui.QAction(MainWindow)
        self.kbAction.setObjectName(_fromUtf8("kbAction"))
        self.xsxkAction = QtGui.QAction(MainWindow)
        self.xsxkAction.setObjectName(_fromUtf8("xsxkAction"))
        self.zyAction = QtGui.QAction(MainWindow)
        self.zyAction.setObjectName(_fromUtf8("zyAction"))
        self.logoutAction = QtGui.QAction(MainWindow)
        self.logoutAction.setObjectName(_fromUtf8("logoutAction"))
        self.userImformationLabel.setBuddy(self.cjTabelView)
        self.xnOpptionLabel.setBuddy(self.xnOpptionComboBox)
        self.xqOpptionLabel.setBuddy(self.xqOpptionComboBox)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "绝望2005第三方登陆系统", None))
        self.welcomePageLabel.setText(_translate("MainWindow", "绝望2005第三方登陆系统欢迎你~", None))
        self.cjPushButton.setText(_translate("MainWindow", "查询成绩", None))
        self.kbPushButton.setText(_translate("MainWindow", "查询课表", None))
        self.yxkcPushButton.setText(_translate("MainWindow", "已选课程", None))
        self.loadingLabel.setText(_translate("MainWindow", "Loading", None))
        self.userImformationLabel.setText(_translate("MainWindow", "<html><head/><body><p>学院 专业  姓名学号</p></body></html>", None))
        self.xnOpptionLabel.setText(_translate("MainWindow", "学年", None))
        self.xnOpptionComboBox.setItemText(0, _translate("MainWindow", "2005-2006", None))
        self.xnOpptionComboBox.setItemText(1, _translate("MainWindow", "2006-2007", None))
        self.xnOpptionComboBox.setItemText(2, _translate("MainWindow", "2007-2008", None))
        self.xnOpptionComboBox.setItemText(3, _translate("MainWindow", "2008-2009", None))
        self.xnOpptionComboBox.setItemText(4, _translate("MainWindow", "2009-2010", None))
        self.xnOpptionComboBox.setItemText(5, _translate("MainWindow", "2010-2011", None))
        self.xnOpptionComboBox.setItemText(6, _translate("MainWindow", "2011-2012", None))
        self.xnOpptionComboBox.setItemText(7, _translate("MainWindow", "2012-2013", None))
        self.xnOpptionComboBox.setItemText(8, _translate("MainWindow", "2013-2014", None))
        self.xqOpptionLabel.setText(_translate("MainWindow", "学期", None))
        self.xqOpptionComboBox.setItemText(0, _translate("MainWindow", "全部学期", None))
        self.xqOpptionComboBox.setItemText(1, _translate("MainWindow", "1", None))
        self.xqOpptionComboBox.setItemText(2, _translate("MainWindow", "2", None))
        self.xqOpptionComboBox.setItemText(3, _translate("MainWindow", "3", None))
        self.lnCjPushButton.setText(_translate("MainWindow", "历年成绩", None))
        self.cjBackPushButton.setText(_translate("MainWindow", "回首页", None))
        self.cjGroupBox_2.setTitle(_translate("MainWindow", "成绩", None))
        self.userGPALabel.setText(_translate("MainWindow", "GPA                                                                    智育", None))
        self.kbImformationLabel.setText(_translate("MainWindow", "本学期   谁谁谁的课表", None))
        self.kbBackPushButton.setText(_translate("MainWindow", "回首页", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "一周课表", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "实践课信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "实习课信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "未安排上课时间的课程", None))
        self.label.setText(_translate("MainWindow", "本学期已成功选取课程", None))
        self.yxkcBackPushButton.setText(_translate("MainWindow", "回首页", None))
        self.yxkcGroupBox.setTitle(_translate("MainWindow", "已选课程", None))
        self.cjAction.setText(_translate("MainWindow", "成绩查询", None))
        self.kbAction.setText(_translate("MainWindow", "课表查询", None))
        self.xsxkAction.setText(_translate("MainWindow", "已选课程", None))
        self.zyAction.setText(_translate("MainWindow", "首页", None))
        self.logoutAction.setText(_translate("MainWindow", "退出", None))
        self.logoutAction.setToolTip(_translate("MainWindow", "退出", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

