# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\unhealthy\Documents\GitHub\myClientPyQt\LoginWidgetQt.ui'
#
# Created: Fri Mar  1 00:09:22 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_loginDialog(object):
    def setupUi(self, loginDialog):
        loginDialog.setObjectName(_fromUtf8("loginDialog"))
        loginDialog.resize(332, 180)
        loginDialog.setMinimumSize(QtCore.QSize(332, 180))
        loginDialog.setMaximumSize(QtCore.QSize(332, 180))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("src/logo_school.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        loginDialog.setWindowIcon(icon)
        loginDialog.setAutoFillBackground(False)
        loginDialog.setSizeGripEnabled(True)
        loginDialog.setModal(False)
        self.verticalLayout_3 = QtGui.QVBoxLayout(loginDialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.stackedWidget = QtGui.QStackedWidget(loginDialog)
        self.stackedWidget.setMinimumSize(QtCore.QSize(331, 191))
        self.stackedWidget.setMaximumSize(QtCore.QSize(331, 191))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout = QtGui.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 10, 10)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.LoginFrame = QtGui.QFrame(self.page)
        self.LoginFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LoginFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.LoginFrame.setObjectName(_fromUtf8("LoginFrame"))
        self.LoginTitleabel = QtGui.QLabel(self.LoginFrame)
        self.LoginTitleabel.setGeometry(QtCore.QRect(1, 1, 332, 41))
        self.LoginTitleabel.setMinimumSize(QtCore.QSize(332, 41))
        self.LoginTitleabel.setMaximumSize(QtCore.QSize(332, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(22)
        font.setItalic(False)
        self.LoginTitleabel.setFont(font)
        self.LoginTitleabel.setScaledContents(False)
        self.LoginTitleabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LoginTitleabel.setObjectName(_fromUtf8("LoginTitleabel"))
        self.userNameLineEdit = QtGui.QLineEdit(self.LoginFrame)
        self.userNameLineEdit.setGeometry(QtCore.QRect(110, 44, 140, 22))
        self.userNameLineEdit.setMinimumSize(QtCore.QSize(140, 22))
        self.userNameLineEdit.setObjectName(_fromUtf8("userNameLineEdit"))
        self.userNamelabel = QtGui.QLabel(self.LoginFrame)
        self.userNamelabel.setGeometry(QtCore.QRect(40, 44, 48, 22))
        self.userNamelabel.setMinimumSize(QtCore.QSize(48, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.userNamelabel.setFont(font)
        self.userNamelabel.setObjectName(_fromUtf8("userNamelabel"))
        self.userCodelabel = QtGui.QLabel(self.LoginFrame)
        self.userCodelabel.setGeometry(QtCore.QRect(50, 87, 32, 22))
        self.userCodelabel.setMinimumSize(QtCore.QSize(32, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.userCodelabel.setFont(font)
        self.userCodelabel.setObjectName(_fromUtf8("userCodelabel"))
        self.userCodeLineEdit = QtGui.QLineEdit(self.LoginFrame)
        self.userCodeLineEdit.setGeometry(QtCore.QRect(110, 87, 140, 22))
        self.userCodeLineEdit.setMinimumSize(QtCore.QSize(140, 22))
        self.userCodeLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.userCodeLineEdit.setObjectName(_fromUtf8("userCodeLineEdit"))
        self.loginButton = QtGui.QPushButton(self.LoginFrame)
        self.loginButton.setGeometry(QtCore.QRect(100, 129, 75, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.loginButton.setObjectName(_fromUtf8("loginButton"))
        self.quitButton = QtGui.QPushButton(self.LoginFrame)
        self.quitButton.setGeometry(QtCore.QRect(180, 129, 75, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.quitButton.setFont(font)
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.gridLayout.addWidget(self.LoginFrame, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 20, 40)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.page_2)
        self.label.setMinimumSize(QtCore.QSize(301, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.progressBar = QtGui.QProgressBar(self.page_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.userNamelabel.setBuddy(self.userNameLineEdit)
        self.userCodelabel.setBuddy(self.userCodeLineEdit)

        self.retranslateUi(loginDialog)
        QtCore.QObject.connect(self.quitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), loginDialog.close)
        QtCore.QMetaObject.connectSlotsByName(loginDialog)
        loginDialog.setTabOrder(self.userNameLineEdit, self.userCodeLineEdit)
        loginDialog.setTabOrder(self.userCodeLineEdit, self.loginButton)
        loginDialog.setTabOrder(self.loginButton, self.quitButton)

    def retranslateUi(self, loginDialog):
        loginDialog.setWindowTitle(_translate("loginDialog", "登陆", None))
        self.LoginTitleabel.setText(_translate("loginDialog", "绝望2005第三方登陆器", None))
        self.userNamelabel.setText(_translate("loginDialog", "用户名", None))
        self.userCodelabel.setText(_translate("loginDialog", "密码", None))
        self.loginButton.setText(_translate("loginDialog", "登陆", None))
        self.quitButton.setText(_translate("loginDialog", "退出", None))
        self.label.setText(_translate("loginDialog", "Loading...", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    loginDialog = QtGui.QDialog()
    ui = Ui_loginDialog()
    ui.setupUi(loginDialog)
    loginDialog.show()
    sys.exit(app.exec_())

